# Generated by Django 4.2 on 2024-05-22 20:42

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('fecha', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=app.models.GetRutaField)),
                ('contraseña', models.CharField(max_length=30)),
                ('certificado', models.FileField(upload_to=app.models.GetRutaField)),
                ('estado', models.CharField(choices=[(1, 'Pendiente'), (2, 'Aprobado'), (3, 'Rechazado')], default='1', max_length=20)),
                ('rol', models.CharField(choices=[(1, 'Estudiante'), (2, 'Administrador')], default='1', max_length=20)),
            ],
        ),
    ]
