# Generated by Django 4.2 on 2024-07-18 22:33

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_documentos_file_alter_usuarios_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/documents/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='certificado',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/certificates/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/photos/'), upload_to=''),
        ),
    ]
