# Generated by Django 4.2 on 2024-06-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuarios_contraseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='contraseña',
            new_name='contrasenia',
        ),
    ]
