# Generated by Django 4.2 on 2024-07-19 21:00

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_documentos_file_alter_usuarios_certificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='certificado',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/certificates'), upload_to='certificates/'),
        ),
    ]
