# Generated by Django 4.2 on 2024-06-30 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usuarios_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='contrasenia',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='nombre',
            new_name='username',
        ),
    ]
