# Generated by Django 4.2 on 2024-07-19 21:22

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_usuarios_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='certificado',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='certificates/'), upload_to=''),
        ),
    ]
