# Generated by Django 4.2 on 2024-07-10 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_usuarios_groups_usuarios_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='nombre',
        ),
        migrations.AddField(
            model_name='documentos',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documentos',
            name='file',
            field=models.FileField(default='default/file/path.txt', upload_to='files/'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentos',
            name='state',
            field=models.CharField(choices=[(1, 'visible'), (2, 'oculto')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='documentos',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
