# Generated by Django 4.2 on 2024-09-19 19:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_documentos_file_alter_usuarios_certificado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentos',
            old_name='created_date',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='documentos',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 9, 19, 19, 46, 4, 33705, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.documentos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
