# Generated by Django 4.2 on 2024-09-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_documentos_file_alter_usuarios_certificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='score_cant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentos',
            name='score_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
