# Generated by Django 4.2 on 2024-09-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_documentos_score_cant_documentos_score_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos',
            name='score_cant',
        ),
        migrations.RemoveField(
            model_name='documentos',
            name='score_sum',
        ),
    ]
