# Generated by Django 4.2 on 2024-09-21 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_carpeta_favorito_denuncia_comentario_and_more'),
        ('app', '0012_remove_documentos_score_cant_and_more'),
    ]

    operations = [
    ]
