# Generated by Django 4.2 on 2024-10-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
