# Generated by Django 4.2 on 2024-10-04 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_materia_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='Materia', to='app.materia'),
            preserve_default=False,
        ),
    ]
