# Generated by Django 4.2 on 2024-10-18 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_carrera_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='departamento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='app.departamento'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CarreraMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.carrera')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.materia')),
            ],
        ),
    ]
